import Script from "next/script";

export const metadata = {
  title: "Stok Takip",
  description: "Generated by OrioNN Development",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="Stok Takip" />
        <meta name="author" content="Kaan Latinler" />
        <link href="../assets/css/pace.min.css" rel="stylesheet" />
        <Script src="../assets/js/pace.min.js" strategy="lazyOnload" />
        <link
          rel="icon"
          href="../assets/images/favicon.ico"
          type="image/x-icon"
        />
        <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />
        <link
          href="../assets/css/animate.css"
          rel="stylesheet"
          type="text/css"
        />
        <link href="../assets/css/icons.css" rel="stylesheet" type="text/css" />
        <link href="../assets/css/app-style.css" rel="stylesheet" />
        <link
          href="../assets/plugins/simplebar/css/simplebar.css"
          rel="stylesheet"
        />
        <link href="../assets/css/sidebar-menu.css" rel="stylesheet" />
      </head>

      <body className="bg-theme bg-theme1">
        {children}

        <Script src="../assets/js/jquery.min.js" strategy="lazyOnload" />
        <Script src="../assets/js/popper.min.js" strategy="lazyOnload" />
        <Script src="../assets/js/bootstrap.min.js" strategy="lazyOnload" />

        <Script
          src="../assets/plugins/simplebar/js/simplebar.js"
          strategy="lazyOnload"
        />

        <Script
          src="../assets/plugins/Chart.js/Chart.min.js"
          strategy="lazyOnload"
        />
        <Script src="../assets/js/index.js" strategy="lazyOnload" />

        <Script src="../assets/js/sidebar-menu.js" strategy="lazyOnload" />

        <Script src="../assets/js/app-script.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
